title: Tim Dailey's Blog
email: timothy.j.dailey@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  TLDR; Notes to Self.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#markdown: kramdown
theme: jekyll-theme-architect
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-gist
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
